#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
DEV="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Dev"

source $DIR/scripts/install-brew
source $DIR/scripts/install-chruby
source $DIR/scripts/install-node
source $DIR/scripts/install-rust

ln -sf $DIR/bashrc $HOME/.bashrc
ln -sf $DIR/bash_profile $HOME/.bash_profile
ln -sf $DIR/dircolors $HOME/.dircolors
ln -sf $DIR/gemrc $HOME/.gemrc
ln -sf $DIR/ruby_version $HOME/.ruby_version
ln -sf $DIR/gitignore $HOME/.gitignore
ln -sf $DIR/wgetrc $HOME/.wgetrc
ln -sf $DIR/psqlrc $HOME/.psqlrc


if [ -d "$DEV" ]
then
  ln -sf "$DEV/ssh" $HOME/.ssh
  ln -sf "$DEV/pgpass" $HOME/.pgpass
  ln -sf "$DEV/pg_service.conf" $HOME/.pg_service.conf
  ln -sf "$DEV/aws" $HOME/.aws

  chmod 600 $HOME/.pgpass
  chmod 700 $HOME/.ssh
  chmod 644 $HOME/.ssh/id_rsa.pub
  chmod 600 $HOME/.ssh/id_rsa
  chmod 644 $HOME/.ssh/authorized_keys
fi
