#!/usr/bin/env bash

export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

ln -sf $DIR/bashrc $HOME/.bashrc
ln -sf $DIR/bash_profile $HOME/.bash_profile
ln -sf $DIR/dircolors $HOME/.dircolors
ln -sf $DIR/fzf.bash $HOME/.fzf.bash
ln -sf $DIR/gemrc $HOME/.gemrc
ln -sf $DIR/ruby_version $HOME/.ruby_version
ln -sf $DIR/gitignore $HOME/.gitignore
ln -sf $DIR/gitconfig $HOME/.gitconfig
ln -sf $DIR/wgetrc $HOME/.wgetrc
ln -sf $DIR/psqlrc $HOME/.psqlrc

  chmod 700 $HOME/.ssh
  chmod 644 $HOME/.ssh/id_rsa.pub
  chmod 600 $HOME/.ssh/id_rsa
  chmod 644 $HOME/.ssh/authorized_keys
