#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install wget git rsync coreutils bash rg bat htop gnu-sed direnv yarn node

touch $HOME/dotfiles/.brew-installed
