#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install wget git rsync coreutils the_silver_searcher bash nnn rg bat htop gnu-sed
