#!/usr/bin/env bash

curl https://sh.rustup.rs -sSf | sh
rustup component add rls rust-analysis rust-src rustfmt clippy
rustup completions bash >rustup.bash-completion
sudo mkdir -p /etc/bash_completion.d
sudo mv rustup.bash-completion /etc/bash_completion.d

touch $HOME/dotfiles/.rust-installed
