#!/usr/bin/env bash

export CHRUBY=0.3.9
export RUBY_INSTALL=0.7.0

wget -O chruby-$CHRUBY.tar.gz https://github.com/postmodern/chruby/archive/v$CHRUBY.tar.gz
tar -xzvf chruby-$CHRUBY.tar.gz
cd chruby-$CHRUBY/
sudo make install
cd -
rm -rf chruby-$CHRUBY*

wget -O ruby-install-$RUBY_INSTALL.tar.gz https://github.com/postmodern/ruby-install/archive/v$RUBY_INSTALL.tar.gz
tar -xzvf ruby-install-$RUBY_INSTALL.tar.gz
cd ruby-install-$RUBY_INSTALL/
sudo make install
cd -
rm -rf ruby-install-$RUBY_INSTALL
rm -rf ruby-install-$RUBY_INSTALL.tar.gz
touch $HOME/dotfiles/.ruby-installed
