#!/usr/bin/env bash
rm -rf "~/Library/Application Support/Code/User"
mkdir -p "~/Library/Application Support/Code/User"
ln -s "$ICLOUD/VSCode/User" "~/Library/Application Support/Code/User"

rm -rf "~/.vscode"
ln -s "$ICLOUD/VSCode/.vscode" "~/.vscode"
