#!/usr/bin/env bash
rm -rf "$HOME/Library/Application Support/Code/User"
mkdir -p "$HOME/Library/Application Support/Code"
ln -s "$ICLOUD/VSCode/User" "$HOME/Library/Application Support/Code/User"

rm -rf "$HOME/.vscode"
ln -s "$ICLOUD/VSCode/.vscode" "$HOME/.vscode"
